### PR TITLE
newPlot not plot

### PR DESCRIPTION
**Pull request by etpinard**
@rreusser I :heart: this thing so much, might as well start contributing to it :wink:

### CODE REVIEW

**Comment by rreusser** [comment]
Love it! What's the benefit of `newPlot` in this context? I'm kinda taking the nuclear option and fully removing and recreating the `gd` element. Unless there are some side effects, is this equivalent? https://github.com/rreusser/plotly-standalone-mock-viewer/blob/master/index.js#L53-L54

**Comment by etpinard** [comment]
`newPlot` calls [`Plotly.purge`](https://github.com/plotly/plotly.js/blob/8ad7e9353409fe5c023a6e03769b9e1d7fad21a0/src/plot_api/plot_api.js#L2792) which clears a bunch of `_` variables on the graph div and calls the relevant gl-vis [`destroy`](https://github.com/gl-vis/gl-plot3d/blob/1fc9a8161d36d57539d009dd042ab413d863cf32/scene.js#L290) methods.

**Comment by rreusser** [comment]
Should I remove the lines that remove the graph div then?

**Comment by etpinard** [comment]
In theory:

```js
var gd = document.getElementById('graph')

Plotly.plot(gd, /* */)
Plotly.purge(gd) 
// => should return gd in pre-Plotly.plot state
```

so _yes_ we don't have to remove the `gd` from the DOM to _clear_ the graph div. But maybe it's better to still remove it from the DOM for GC purposes. I'll let you decide what's best.

**Pull request merged**
